"""add delivered column to notifications

Revision ID: 830080ea8f8b
Revises: 3132e280edfa
Create Date: 2026-01-17 15:44:56.524114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830080ea8f8b'
down_revision = '3132e280edfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'delivered')
    # ### end Alembic commands ###
