"""add fcm_token to users

Revision ID: 31ba1f80814c
Revises: cf559d72b2b3
Create Date: 2026-01-06 07:08:55.903709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31ba1f80814c'
down_revision = 'cf559d72b2b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle dependency: Drop foreign key from students first
    op.drop_constraint('students_college_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'college_id')

    op.drop_index(op.f('ix_colleges_code'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_table('colleges')
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('users', 'fcm_token')
    op.create_table('colleges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('colleges_pkey'))
    )
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_index(op.f('ix_colleges_code'), 'colleges', ['code'], unique=True)
    # ### end Alembic commands ###
